[project]
name = "bv_nodepack"
version = "0.0.3"
description = "Collection of supply nodes (pipes, etc.) for better workflow management."
authors = [
  {name = "BlackVortex", email = "blackvortexx@proton.me"}
]
readme = "README.md"
license = {text = "GNU General Public License v3"}


[project.urls]
Repository = "https://github.com/BlackVortexAI/bv_nodepack"
BugTracker = "https://github.com/BlackVortexAI/bv_nodepack/issues"
Documentation = "https://github.com/BlackVortexAI/bv_nodepack/wiki"


[tool.comfy]
PublisherId = "blackvortex"
DisplayName = "BV-NodePack"
Icon = ""
